create table if not exists public.productivity_records (
  id bigint generated by default as identity primary key,
  fecha date not null,
  operador text not null,
  turno text not null,
  actividad text not null,
  hora integer not null default 0,
  lineas_preparadas numeric not null default 0,
  toneladas_preparadas numeric not null default 0,
  horas_productivas numeric not null default 0,
  incidencias numeric not null default 0,
  meta_lineas_hora numeric not null default 20,
  batch_id text not null,
  created_at timestamptz not null default now(),
  unique (batch_id, fecha, operador, turno, actividad, hora)
);

alter table public.productivity_records
  add column if not exists hora integer not null default 0;

alter table public.productivity_records
  drop constraint if exists productivity_records_batch_id_fecha_operador_turno_actividad_key;

alter table public.productivity_records
  drop constraint if exists productivity_records_batch_fecha_operador_turno_actividad_hora_key;

alter table public.productivity_records
  drop constraint if exists productivity_records_batch_id_fecha_operador_turno_actividad_hora_key;

alter table public.productivity_records
  add constraint productivity_records_batch_fecha_operador_turno_actividad_hora_key
  unique (batch_id, fecha, operador, turno, actividad, hora);

create index if not exists productivity_records_fecha_idx
  on public.productivity_records (fecha);

alter table public.productivity_records enable row level security;

drop policy if exists "authenticated users can read productivity"
  on public.productivity_records;
drop policy if exists "authenticated users can insert productivity"
  on public.productivity_records;
drop policy if exists "authenticated users can update productivity"
  on public.productivity_records;

create policy "authenticated users can read productivity"
  on public.productivity_records for select to authenticated using (true);

create policy "authenticated users can insert productivity"
  on public.productivity_records for insert to authenticated with check (true);

create policy "authenticated users can update productivity"
  on public.productivity_records for update to authenticated using (true) with check (true);
